---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dohewjes/public_html/blog
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    #- export REPOPATH=/home/dohewjes/repositories/JDCS-blog
    #- /rm -Rf ${DEPLOYPATH}_old
    #- /cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    #- /rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
    #- /chmod 755 ${DEPLOYPATH}
    #- /find ${DEPLOYPATH} -type d -exec /chmod 755 '{}' \;
    #- /find ${DEPLOYPATH} -type f -exec /chmod 644 '{}' \;