---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dohertyjoe198/public_html/blog/
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp blogs.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    #- export REPOPATH=/home/dohertyjoe198/repositories/JDCS-blog/
    #- /rm -Rf ${DEPLOYPATH}_old
    #- /cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    #- /rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
    #- /chmod 755 ${DEPLOYPATH}
    #- /find ${DEPLOYPATH} -type d -exec /chmod 755 '{}' \;
    #- /find ${DEPLOYPATH} -type f -exec /chmod 644 '{}' \;